"""
Base Strategy — All trading strategies inherit from this.
=========================================================
To create a new strategy:
1. Create a new file in /strategies (e.g., my_strategy.py)
2. Inherit from BaseStrategy
3. Implement the `check_signal()` method
4. Register it in scanner.py
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class Signal:
    """
    A trading signal generated by a strategy.
    Contains everything needed to execute a trade.
    """
    stock: str                    # Stock symbol (e.g., "RELIANCE")
    token: str                    # Angel One instrument token
    direction: str                # "LONG" or "SHORT"
    entry_price: float            # Recommended entry price
    stop_loss: float              # Stop-loss price
    target: float                 # Target price
    strategy_name: str            # Which strategy generated this
    confidence: float = 0.0       # 0-1 score (higher = stronger signal)
    reason: str = ""              # Human-readable explanation
    timestamp: datetime = None    # When the signal was generated
    quantity: int = 0             # Shares to buy (filled by risk manager)

    # ── Sniper mode fields ───────────────────────────────────────────
    score: int = 0                # Signal score 0-100 (filled by scorer)
    score_breakdown: dict = None  # Per-factor breakdown (filled by scorer)
    confluence_count: int = 0     # How many strategies agree (sniper mode)
    confluence_strategies: list = None  # List of agreeing strategy names
    atr_value: float = 0.0       # ATR(14) on 5-min candles at signal time
    choppiness: float = 0.0      # Choppiness Index at signal time
    trend_15m: str = ""           # 15-min trend: "BULLISH"/"BEARISH"/"NEUTRAL"
    skip_reason: str = ""         # Why signal was skipped (for logging)
    status: str = "PENDING"       # EXECUTED/QUEUED/SKIPPED-* (signal queue)

    # ── Volume profile fields (TOD RVOL) ──────────────────────────────
    rvol: float = 0.0            # Relative Volume vs TOD average (or session avg fallback)
    adv: float = 0.0             # Average Daily Volume (20-day, shares)
    macro_driven: bool = False   # True if NIFTY RVOL >= 2x at same time (macro event)

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()
        if self.score_breakdown is None:
            self.score_breakdown = {}
        if self.confluence_strategies is None:
            self.confluence_strategies = []

    @property
    def risk_points(self) -> float:
        """How many points between entry and stop-loss."""
        return abs(self.entry_price - self.stop_loss)

    @property
    def reward_points(self) -> float:
        """How many points between entry and target."""
        return abs(self.target - self.entry_price)

    @property
    def risk_reward_ratio(self) -> float:
        """Reward ÷ Risk. We want this ≥ 1.5."""
        if self.risk_points == 0:
            return 0
        return round(self.reward_points / self.risk_points, 2)

    def to_dict(self) -> dict:
        """Convert to dictionary (for Firebase)."""
        return {
            "stock": self.stock,
            "direction": self.direction,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "target": self.target,
            "strategy": self.strategy_name,
            "confidence": self.confidence,
            "reason": self.reason,
            "risk_reward": self.risk_reward_ratio,
            "quantity": self.quantity,
            "timestamp": self.timestamp.isoformat(),
            "score": self.score,
            "confluence_count": self.confluence_count,
            "confluence_strategies": self.confluence_strategies,
            "atr_value": self.atr_value,
            "choppiness": self.choppiness,
            "trend_15m": self.trend_15m,
            "status": self.status,
            "skip_reason": self.skip_reason,
            "rvol": self.rvol,
            "adv": self.adv,
            "macro_driven": self.macro_driven,
        }

    def __str__(self) -> str:
        return (
            f"{self.direction} {self.stock} @ ₹{self.entry_price:.2f} | "
            f"SL: ₹{self.stop_loss:.2f} | Target: ₹{self.target:.2f} | "
            f"RR: 1:{self.risk_reward_ratio} | Strategy: {self.strategy_name}"
        )


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    Every strategy must implement `check_signal()` which receives
    current market data and returns a Signal if conditions are met,
    or None if no setup is found.
    """

    def __init__(self, name: str):
        self.name = name
        self.is_active = True

    @abstractmethod
    def check_signal(
        self,
        stock: str,
        token: str,
        candles: "pd.DataFrame",     # Historical candles (OHLCV)
        current_tick: dict,           # Latest price tick
        market_context: dict,         # NIFTY direction, etc.
    ) -> Optional[Signal]:
        """
        Analyze data and return a Signal if conditions are met.
        
        Args:
            stock: Stock symbol (e.g., "RELIANCE")
            token: Angel One instrument token
            candles: DataFrame with columns [Open, High, Low, Close, Volume]
            current_tick: Latest tick {ltp, open, high, low, close, volume}
            market_context: {nifty_direction: "BULLISH"/"BEARISH"/"NEUTRAL", ...}
        
        Returns:
            Signal if setup found, None otherwise
        """
        pass

    def __repr__(self):
        status = "Active" if self.is_active else "Inactive"
        return f"<Strategy: {self.name} ({status})>"
