"""
Base Strategy — All trading strategies inherit from this.
=========================================================
To create a new strategy:
1. Create a new file in /strategies (e.g., my_strategy.py)
2. Inherit from BaseStrategy
3. Implement the `check_signal()` method
4. Register it in scanner.py
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class Signal:
    """
    A trading signal generated by a strategy.
    Contains everything needed to execute a trade.
    """
    stock: str                    # Stock symbol (e.g., "RELIANCE")
    token: str                    # Angel One instrument token
    direction: str                # "LONG" or "SHORT"
    entry_price: float            # Recommended entry price
    stop_loss: float              # Stop-loss price
    target: float                 # Target price
    strategy_name: str            # Which strategy generated this
    confidence: float = 0.0       # 0-1 score (higher = stronger signal)
    reason: str = ""              # Human-readable explanation
    timestamp: datetime = None    # When the signal was generated
    quantity: int = 0             # Shares to buy (filled by risk manager)

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now()

    @property
    def risk_points(self) -> float:
        """How many points between entry and stop-loss."""
        return abs(self.entry_price - self.stop_loss)

    @property
    def reward_points(self) -> float:
        """How many points between entry and target."""
        return abs(self.target - self.entry_price)

    @property
    def risk_reward_ratio(self) -> float:
        """Reward ÷ Risk. We want this ≥ 1.5."""
        if self.risk_points == 0:
            return 0
        return round(self.reward_points / self.risk_points, 2)

    def to_dict(self) -> dict:
        """Convert to dictionary (for Firebase)."""
        return {
            "stock": self.stock,
            "direction": self.direction,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "target": self.target,
            "strategy": self.strategy_name,
            "confidence": self.confidence,
            "reason": self.reason,
            "risk_reward": self.risk_reward_ratio,
            "quantity": self.quantity,
            "timestamp": self.timestamp.isoformat(),
        }

    def __str__(self) -> str:
        return (
            f"{self.direction} {self.stock} @ ₹{self.entry_price:.2f} | "
            f"SL: ₹{self.stop_loss:.2f} | Target: ₹{self.target:.2f} | "
            f"RR: 1:{self.risk_reward_ratio} | Strategy: {self.strategy_name}"
        )


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    Every strategy must implement `check_signal()` which receives
    current market data and returns a Signal if conditions are met,
    or None if no setup is found.
    """

    def __init__(self, name: str):
        self.name = name
        self.is_active = True

    @abstractmethod
    def check_signal(
        self,
        stock: str,
        token: str,
        candles: "pd.DataFrame",     # Historical candles (OHLCV)
        current_tick: dict,           # Latest price tick
        market_context: dict,         # NIFTY direction, etc.
    ) -> Optional[Signal]:
        """
        Analyze data and return a Signal if conditions are met.
        
        Args:
            stock: Stock symbol (e.g., "RELIANCE")
            token: Angel One instrument token
            candles: DataFrame with columns [Open, High, Low, Close, Volume]
            current_tick: Latest tick {ltp, open, high, low, close, volume}
            market_context: {nifty_direction: "BULLISH"/"BEARISH"/"NEUTRAL", ...}
        
        Returns:
            Signal if setup found, None otherwise
        """
        pass

    def __repr__(self):
        status = "Active" if self.is_active else "Inactive"
        return f"<Strategy: {self.name} ({status})>"
